# Generated by Django 4.1 on 2022-09-05 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ControlPersonal', '0025_remove_asistencia_number_hour'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bodega',
            options={'verbose_name': 'Inventario Real', 'verbose_name_plural': 'Inventarios Reales'},
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='time_in',
            field=models.TimeField(auto_now=True, verbose_name='Hora entrada'),
        ),
    ]
